name: safdp_app
description: SAFDP Application

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  carousel_slider: ^1.3.0
  firebase_core: #^0.4.3+1
  firebase_database: ^3.1.1 #^0.4.6
  photo_view: ^0.9.1
  #firebase_messaging: #Notification
  intl: ^0.16.1 #Date
  url_launcher: ^5.4.2 #HyperLink

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"
  flutter_launcher_name: "^0.0.1"

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/SAFDP_Logo.jpg"

flutter_launcher_name:
  name: "SAFDP"

 
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

    #Template & Homepage
    - assets/SAFDay_Banner.jpg 
    - assets/Messages_Banner.jpg
    - assets/CnS_Banner.jpg
    - assets/FunFact_Banner.jpg
    - assets/UsefulInfo_Banner.jpg

    #Message
    - assets/GeneralAnnoucements_Banner.jpg
    - assets/SafetyMessage_Banner.jpg
    - assets/TrainerMessage_Banner.jpg
    - assets/AttendenceTaking_Banner.jpg

    #SAFDayParade2020
    - assets/KAH_Banner.jpg
    - assets/KahParade_Banner.jpg
    - assets/KahOrganising_Banner.jpg
    - assets/Feedback_Banner.jpg 
    - assets/HistoryOfSAF_Banner.jpg
    - assets/SAF.jpg
    - assets/HistoryOfSAFParade_Banner.jpg
    - assets/History_BirthOfSAF_Banner.jpg
    - assets/History_Earlyyears_Banner.jpg
    - assets/History_MaturingSAF_Banner.jpg
    - assets/History_WW2_Banner.jpg
    - assets/SAFFirstParade.jpg
    - assets/KAH_ColorRSM.jpg
    - assets/KAH_ConductingWarrant1.jpg
    - assets/KAH_ConductingWarrant2.jpg
    - assets/KAH_DirectorOfMusic.jpg
    - assets/KAH_PacChairman.jpg
    - assets/KAH_PacDyChairman1.jpg
    - assets/KAH_PacDyChairman2.jpg
    - assets/KAH_Parade2IC.jpg
    - assets/KAH_ParadeCommander.jpg
    - assets/KAH_ParadeCommanderReserve.jpg
    - assets/KAH_ParadeRSM.jpg
    - assets/KAH_ParadeRSMReserve.jpg
    - assets/KAH_SAFDPChairman.jpg
    - assets/KAH_SAFDPdyChairman.jpg
    - assets/KAH_SAFDPdyChairman2.jpg

    #CnS
    - assets/CnS_Introduction_Banner.jpg
    - assets/CnS_History_Banner.jpg
    - assets/CnS_ColorStates_Banner.jpg
    - assets/CnS_Colors_Banner.jpg
    - assets/CnS_PresidentFlag_Banner.jpg
    - assets/CnS_PaceStick_Banner.jpg
    - assets/CnS_CeremonialSword_Banner.jpg
    - assets/CnS_History.jpg
    - assets/CnS_ColorsInDisplay.jpg
    - assets/CnS_ColorStates_NDPDisplay.png
    - assets/CnS_ColorStates_PresidentFlag.png
    - assets/CnS_ColorStates_RSAF.png
    - assets/CnS_ColorStates_RSN.png
    - assets/CnS_ColorStates_SAF.png
    - assets/CnS_ColorStates_SAFBand.png
    - assets/CnS_ColorStates_SAFTI.png
    - assets/CnS_CeremonialSword.png
    - assets/CnS_PaceStick.png
    - assets/Colors_ConsecrationOfColor.jpg
    - assets/Colors_ComplementAndSalute.jpg
    - assets/CnS_UniformNo1_Banner.jpg  
    - assets/CnS_UniformNo1_1.jpg
    - assets/CnS_UniformNo1_2.jpg
    - assets/CnS_UniformNo1_3.jpg
    - assets/CnS_UniformNo1_4.jpg
    - assets/CnS_UniformNo1_5.jpg
    - assets/CnS_UniformNo1_6.jpg
    - assets/CnS_UniformNo1_7.jpg
    - assets/CnS_UniformNo1_8.jpg
    - assets/CnS_UniformNo1_9.jpg
    - assets/CnS_UniformNo1_10.jpg
    - assets/CnS_UniformNo1_11.jpg
    - assets/CnS_UniformNo1_12.jpg
    - assets/CnS_UniformNo1_13.jpg
    - assets/CnS_UniformNo1_14.jpg
    - assets/CnS_UniformNo4_Banner.jpg
    - assets/CnS_UniformNo4_1.jpg
    - assets/CnS_UniformNo4_2.jpg
    - assets/CnS_UniformNo4_3.jpg
    - assets/CnS_UniformNo4_4.jpg
    - assets/CnS_UniformNo4_5.jpg
    - assets/CnS_UniformNo4_6.jpg

    #Programmes
    - assets/Programmes_Banner.jpg
    - assets/ActualDay_Banner.jpg
    - assets/CombineRehearsal_Banner.jpg
    - assets/ComponentTraining_Banner.jpg
    - assets/RehearsalSchedule_Banner.jpg
    - assets/CR_WarmUp.jpg
    - assets/CR_MarchIn.jpg
    - assets/CR_Run1.jpg
    - assets/CR_Run2.jpg
    - assets/ActualDay_1.jpg
    - assets/ActualDay_2.jpg
    - assets/ActualDay_3.jpg
    - assets/ActualDay_4.jpg
    - assets/ActualDay_5.jpg

    #Useful Information
    - assets/UsefulInfo_HeatPrevention_Banner.jpg
    - assets/UsefulInfo_HeatPrevention1.jpg
    - assets/UsefulInfo_HeatPrevention2.jpg
    - assets/UsefulInfo_HeatPrevention3.jpg
    - assets/UsefulInfo_HeatPrevention4.jpg
    - assets/UsefulInfo_HeatPrevention5.jpg
    - assets/UsefulInfo_HeatPrevention6.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
